### ISSUE TITLE
Forms - examples

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-docs#49] opened 2015-08-21 10:31 UTC
Radio buttons and Checkboxes need to go one after the other. Currently one's at the top the other's at the bottom.

**Comment by dominikwilkowski** [comment] 2015-08-21 11:06
that's not possible in the current build... might have to rethink things...

**Comment by dominikwilkowski** [comment] 2016-02-10 01:16
Closing as duplicate of WestpacCXTeam/GUI-source#117

**Closed by dominikwilkowski** 2016-02-10 01:16 UTC
Labels: enhancement
