### ISSUE TITLE
Checkboxes not visible on the blender page and broken in Checkbox module in Firefox Mac (haven't tested windows)

### ISSUE THREAD

**Issue by KateMacdonald** [WestpacCXTeam/GUI-docs#67] opened 2015-09-16 01:26 UTC
So if you're looking at the blender in Firefox - you can't add modules.

**Comment by dominikwilkowski** [comment] 2015-09-16 03:16
closing as duplicate of #58

**Closed by dominikwilkowski** 2015-09-16 03:16 UTC
Labels: bug
